FORMAT: 1A
HOST: http://127.0.0.1:8000

# Machines

## Machines collection [/machines]

### Get Machines [GET]

+ Response 200 (application/json; charset=utf-8)

### Save Machines [POST]

+ Response 201 (text/plain)
